FROM php:8.0-apache

LABEL authors="davide"

RUN a2enmod headers rewrite

RUN apt-get update \
    && apt-get install -y libpq-dev \
    && docker-php-ext-install mysqli pdo_mysql \
    && docker-php-ext-enable mysqli \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY . /var/www/html